services:
  gazebo_simulator:
    build:
      context: .
      dockerfile: Dockerfile
      
    image: gazebo_sim_img
    
    container_name: gazebo_simulator
    
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /home/${USER}/Desktop/Brain:/root/bfmc
      - /run/udev:/run/udev:ro
      
    devices:
      - /dev/input:/dev/input

    # Uncomment the following lines if you want to connect to ros from the host
    #ports:
    #  - 11311:11311
      
    # network_mode: host
    privileged: true
    stdin_open: true
    tty: true
    shm_size: '8gb'
