services:
  ros:
    build:
      context: .
      dockerfile: Dockerfile.noetic
    image: bfmc2025
    container_name: bfmc2025_container
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - shared-volume:/tmp
      - ../../Brain/brain/src:/catkin_ws/src
    tty: true
    privileged: true
    environment:
      - DISPLAY=$DISPLAY 
      - ROS_DISTRO=noetic
      - LD_LIBRARY_PATH=/opt/vc/lib
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
      - /dev/ttyACM1:/dev/ttyACM1
      - /dev/gpiomem:/dev/gpiomem
      - /dev/mem:/dev/mem
    #command: /bin/bash -c "source /opt/ros/noetic/setup.bash && source /catkin_ws/devel/setup.bash && bash"
    command: tail -f /dev/null

    
  picamera:
    build:
      context: .
      dockerfile: Dockerfile.picamera
    image: bfmc2025_picamera2
    container_name: bfmc2025_picamera2_container
    volumes:
      - shared-volume:/tmp
      - /run/udev:/run/udev:ro
      - ./picam:/app
    tty: true
    privileged: true
    #command: python3 "client.py"
    command: tail -f /dev/null

volumes:
  shared-volume:
    driver: local
