services:
  ros:
    build:
      context: .
      dockerfile: Dockerfile.noetic
    image: bfmc2025
    container_name: bfmc2025_container
    volumes:
      - /tmp:/tmp
      - /home/${USER}/Desktop/Brain/brain/src:/catkin_ws/src
      - /dev/shm:/dev/shm
    working_dir: /catkin_ws/src/smart
    tty: true
    privileged: true
    environment:
      - DISPLAY=$DISPLAY 
      - ROS_DISTRO=noetic
      - LD_LIBRARY_PATH=/opt/vc/lib
    devices:
      - /dev:/dev
    command: tail -f /dev/null

    
  picamera:
    build:
      context: .
      dockerfile: Dockerfile.picamera
    image: bfmc2025_picamera2
    container_name: bfmc2025_picamera2_container
    volumes:
      - /tmp:/tmp
      - /run/udev:/run/udev:ro
      - ./picam:/app
    working_dir: /app
    tty: true
    privileged: true
    command: bash -c "python3 camera_server.py"  # tail -f /dev/null
    restart: unless-stopped               # automatic restart policy

volumes:
  shared-volume:
    driver: local
